from financial_calculations import FinancialCalculations

def display_menu():
    print("Which formula would you like to use?")
    print("1. Simple Interest Future Value (FV)")
    print("2. Simple Interest Present Value (PV)")
    print("3. Simple Interest Rate (r)")
    print("4. Compound Interest Future Value (FV)")
    print("5. Compound Interest Present Value (PV)")
    print("6. Compound Interest Rate (r)")
    print("7. Periodic Interest Future Value (FV)")
    print("8. Periodic Interest Present Value (PV)")
    print("9. Periodic Interest Rate (r)")
    print("10. Continuous Interest Future Value (FV)")
    print("11. Continuous Interest Present Value (PV)")
    print("12. Continuous Interest Rate (r)")
    print("13. Interest with Periodic Deposit Future Value (FV)")

def process_choice(choice):
    if choice == 1:
        print("Recall: PV = Present Value, r = Interest Rate, n = Number of Periods")
        inputs = input("Enter PV, r, n separated by spaces: ").split()
        pv = float(inputs[0])
        r = float(inputs[1])
        n = int(inputs[2])
        fv = FinancialCalculations.fv_simple(pv, r, n)
        print(f"Future Value: {fv}")
        print(f"You will have {fv} in {n} years with a simple interest rate of {r * 100}%.")
    elif choice == 2:
        print("Recall: FV = Future Value, r = Interest Rate, n = Number of Periods")
        inputs = input("Enter FV, r, n separated by spaces: ").split()
        fv = float(inputs[0])
        r = float(inputs[1])
        n = int(inputs[2])
        pv = FinancialCalculations.pv_simple(fv, r, n)
        print(f"Present Value: {pv}")
        print(f"To have {fv} in {n} years with a simple interest rate of {r * 100}%, you need to invest {pv} today.")
    elif choice == 3:
        print("Recall: PV = Present Value, FV = Future Value, n = Number of Periods")
        inputs = input("Enter PV, FV, n separated by spaces: ").split()
        pv = float(inputs[0])
        fv = float(inputs[1])
        n = int(inputs[2])
        r = FinancialCalculations.r_simple(pv, fv, n)
        print(f"Interest Rate: {r}")
        print(f"To grow an investment from {pv} to {fv} in {n} years, you need an interest rate of {r * 100}% per year.")
    elif choice == 4:
        print("Recall: PV = Present Value, r = Interest Rate, n = Number of Periods")
        inputs = input("Enter PV, r, n separated by spaces: ").split()
        pv = float(inputs[0])
        r = float(inputs[1])
        n = int(inputs[2])
        fv = FinancialCalculations.fv_compound(pv, r, n)
        print(f"Future Value: {fv}")
        print(f"You will have {fv} in {n} years with a compound interest rate of {r * 100}%.")
    elif choice == 5:
        print("Recall: FV = Future Value, r = Interest Rate, n = Number of Periods")
        inputs = input("Enter FV, r, n separated by spaces: ").split()
        fv = float(inputs[0])
        r = float(inputs[1])
        n = int(inputs[2])
        pv = FinancialCalculations.pv_compound(fv, r, n)
        print(f"Present Value: {pv}")
        print(f"To have {fv} in {n} years with a compound interest rate of {r * 100}%, you need to invest {pv} today.")
    elif choice == 6:
        print("Recall: PV = Present Value, FV = Future Value, n = Number of Periods")
        inputs = input("Enter PV, FV, n separated by spaces: ").split()
        pv = float(inputs[0])
        fv = float(inputs[1])
        n = int(inputs[2])
        r = FinancialCalculations.r_compound(pv, fv, n)
        print(f"Interest Rate: {r}")
        print(f"To grow an investment from {pv} to {fv} in {n} years with compound interest, you need an interest rate of {r * 100}% per year.")
    elif choice == 7:
        print("Recall: PV = Present Value, r = Interest Rate, n = Number of Periods, m = Compounding Periods per Year")
        inputs = input("Enter PV, r, n, m separated by spaces: ").split()
        pv = float(inputs[0])
        r = float(inputs[1])
        n = int(inputs[2])
        m = int(inputs[3])
        fv = FinancialCalculations.fv_interval(pv, r, n, m)
        print(f"Future Value: {fv}")
        print(f"You will have {fv} in {n} years with periodic compounding {m} times a year at an interest rate of {r * 100}%.")
    elif choice == 8:
        print("Recall: FV = Future Value, r = Interest Rate, n = Number of Periods, m = Compounding Periods per Year")
        inputs = input("Enter FV, r, n, m separated by spaces: ").split()
        fv = float(inputs[0])
        r = float(inputs[1])
        n = int(inputs[2])
        m = int(inputs[3])
        pv = FinancialCalculations.pv_interval(fv, r, n, m)
        print(f"Present Value: {pv}")
        print(f"To have {fv} in {n} years with periodic compounding {m} times a year at an interest rate of {r * 100}%, you need to invest {pv} today.")
    elif choice == 9:
        print("Recall: PV = Present Value, FV = Future Value, n = Number of Periods, m = Compounding Periods per Year")
        inputs = input("Enter PV, FV, n, m separated by spaces: ").split()
        pv = float(inputs[0])
        fv = float(inputs[1])
        n = int(inputs[2])
        m = int(inputs[3])
        r = FinancialCalculations.r_interval(pv, fv, n, m)
        print(f"Interest Rate: {r}")
        print(f"To grow an investment from {pv} to {fv} in {n} years with periodic compounding {m} times a year, you need an interest rate of {r * 100}% per year.")
    elif choice == 10:
        print("Recall: PV = Present Value, r = Interest Rate, n = Number of Periods")
        inputs = input("Enter PV, r, n separated by spaces: ").split()
        pv = float(inputs[0])
        r = float(inputs[1])
        n = int(inputs[2])
        fv = FinancialCalculations.fv_continuous(pv, r, n)
        print(f"Future Value: {fv}")
        print(f"You will have {fv} in {n} years with continuous compounding at an interest rate of {r * 100}%.")
    elif choice == 11:
        print("Recall: FV = Future Value, r = Interest Rate, n = Number of Periods")
        inputs = input("Enter FV, r, n separated by spaces: ").split()
        fv = float(inputs[0])
        r = float(inputs[1])
        n = int(inputs[2])
        pv = FinancialCalculations.pv_continuous(fv, r, n)
        print(f"Present Value: {pv}")
        print(f"To have {fv} in {n} years with continuous compounding at an interest rate of {r * 100}%, you need to invest {pv} today.")
    elif choice == 12:
        print("Recall: PV = Present Value, FV = Future Value, n = Number of Periods")
        inputs = input("Enter PV, FV, n separated by spaces: ").split()
        pv = float(inputs[0])
        fv = float(inputs[1])
        n = int(inputs[2])
        r = FinancialCalculations.r_continuous(pv, fv, n)
        print(f"Interest Rate: {r}")
        print(f"To grow an investment from {pv} to {fv} in {n} years with continuous compounding, you need an interest rate of {r * 100}% per year.")
    elif choice == 13:
        print("Recall: r = Interest Rate, n = Number of Periods, m = Compounding Periods per Year, A = Amount Deposited Periodically")
        inputs = input("Enter r, n, m, A separated by spaces: ").split()
        r = float(inputs[0])
        n = int(inputs[1])
        m = int(inputs[2])
        a = float(inputs[3])
        fv = FinancialCalculations.fv_with_deposit(r, n, m, a)
        print(f"Future Value with Periodic Deposit: {fv}")
        print(f"With periodic deposits of {a} every period, you will have {fv} in {n} years, compounding {m} times a year at an interest rate of {r * 100}%.")
    else:
        print("Invalid choice. Please select a valid formula number.")
